const fs = require('fs');
const path = require('path');

function calculateNextVersion(currentVersion, bumpType) {
  if (/^\d+\.\d+\.\d+$/.test(bumpType)) {
    return bumpType;
  }
  const parts = currentVersion.split('.').map(Number);
  if (parts.length !== 3 || parts.some(isNaN)) {
    throw new Error(`Invalid semver version: ${currentVersion}`);
  }
  let [major, minor, patch] = parts;
  switch (bumpType) {
    case 'major':
      major += 1;
      minor = 0;
      patch = 0;
      break;
    case 'minor':
      minor += 1;
      patch = 0;
      break;
    case 'patch':
    default:
      patch += 1;
      break;
  }
  return `${major}.${minor}.${patch}`;
}

function updateVersions(rootDir, nextVersion, nextBuildNumber) {
  const packageJsonPath = path.join(rootDir, 'package.json');
  const buildGradlePath = path.join(rootDir, 'android/app/build.gradle');
  const pbxprojPath = path.join(rootDir, 'ios/remusapprecorder.xcodeproj/project.pbxproj');
  const watchPlistPath = path.join(rootDir, 'ios/RemusWatch/Info.plist');
  const versionTsPath = path.join(rootDir, 'src/version.ts');

  // 1. package.json
  const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  const oldVersion = pkg.version;
  pkg.version = nextVersion;
  fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');

  // 2. android/app/build.gradle
  let gradleContent = fs.readFileSync(buildGradlePath, 'utf8');
  gradleContent = gradleContent.replace(/versionCode\s+\d+/, `versionCode ${nextBuildNumber}`);
  gradleContent = gradleContent.replace(/versionName\s+"[^"]+"/, `versionName "${nextVersion}"`);
  fs.writeFileSync(buildGradlePath, gradleContent, 'utf8');

  // 3. ios project.pbxproj
  let pbxContent = fs.readFileSync(pbxprojPath, 'utf8');
  pbxContent = pbxContent.replace(/MARKETING_VERSION\s*=\s*[^;]+;/g, `MARKETING_VERSION = ${nextVersion};`);
  pbxContent = pbxContent.replace(/CURRENT_PROJECT_VERSION\s*=\s*[^;]+;/g, `CURRENT_PROJECT_VERSION = ${nextBuildNumber};`);
  fs.writeFileSync(pbxprojPath, pbxContent, 'utf8');

  // 4. ios/RemusWatch/Info.plist
  let watchPlist = fs.readFileSync(watchPlistPath, 'utf8');
  watchPlist = watchPlist.replace(
    /<key>CFBundleShortVersionString<\/key>\s*<string>[^<]*<\/string>/,
    '<key>CFBundleShortVersionString</key>\n\t<string>$(MARKETING_VERSION)</string>'
  );
  watchPlist = watchPlist.replace(
    /<key>CFBundleVersion<\/key>\s*<string>[^<]*<\/string>/,
    '<key>CFBundleVersion</key>\n\t<string>$(CURRENT_PROJECT_VERSION)</string>'
  );
  fs.writeFileSync(watchPlistPath, watchPlist, 'utf8');

  // 5. src/version.ts
  const versionTs = `// Auto-generated by scripts/versionManager.js - DO NOT EDIT MANUALLY
export const APP_VERSION = '${nextVersion}';
export const APP_BUILD_NUMBER = ${nextBuildNumber};
export const APP_DISPLAY_VERSION = 'v${nextVersion} (${nextBuildNumber})';
`;
  fs.writeFileSync(versionTsPath, versionTs, 'utf8');

  return { oldVersion, newVersion: nextVersion, buildNumber: nextBuildNumber };
}

module.exports = {
  calculateNextVersion,
  updateVersions
};
